server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/darkness_db?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        globally_quoted_identifiers: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

secret:
  key: ${JWT_SECRET:1234567890qwertyuiop}
